language: c++

os:
  - linux
  - osx

compiler:
  - gcc

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] sudo apt-get update && sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev; fi
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1.tar.bz2
  - tar jxf wxWidgets-3.1.1.tar.bz2
  - cd wxWidgets-3.1.1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd wxWidgets-3.1.1 && ./configure --prefix=$HOME/wx-3.1.1 ./configure --prefix=/path/to/wxWidgets-3.1.1/release-build --enable-shared=no --enable-stl=yes --enable-debug=no --with-gtk=2 --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --with-expat=builtin --without-libjbig --without-liblzma --without-gtkprint --with-libnotify=no --with-libmspack=no --with-gnomevfs=no --with-opengl=yes --with-sdl=no --with-cxx=11); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (./configure --prefix=$HOME/wx-3.1.1 --enable-stl=yes --enable-debug=no --enable-shared=no --with-cocoa --enable-macosx_arch=x86_64 --enable-unicode --enable-webview --with-cxx=11 --with-macosx-version-min=10.9  --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --with-expat=builtin --disable-mediactrl); fi
  - make -j2 all install
  - sudo ln -s $HOME/wx-3.1.1/bin/wx-config /usr/local/bin/wx-config-3
  - cd ../
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LKDIR=/home/travis/build/$user/lk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LKDIR=/Users/travis/build/$user/lk; fi
  - git clone https://github.com/nrel/lk.git $LKDIR

script:
  - export PATH=$PATH:$HOME/wx-3.1.1/bin
  - pwd
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j2 -C $LKDIR/build_linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j2 -C $WEXDIR/build_linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -j2 -C $LKDIR/build_osx; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -j2 -C $WEXDIR/build_osx; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgtk-3-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 
branches:
  only:
  - master
  - develop
  