language: c++

os:
  - linux
  - osx

compiler:
  - gcc

before_script:
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2
  - tar jxf wxWidgets-3.1.0.tar.bz2
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd wxWidgets-3.1.0 && ./configure --prefix=$HOME/wx-3.1.0 && make -j2 all install); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd wxWidgets-3.1.0 && ./configure --prefix=$HOME/wx-3.1.0 --enable-stl=yes --enable-debug=no --enable-shared=no --with-cocoa --enable-macosx_arch=x86_64 --enable-unicode --enable-webview --with-cxx=11 --with-macosx-version-min=10.9  --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --with-expat=builtin --disable-qtkit --disable-mediactrl   && make -j2 all install); fi
  - ln -s $HOME/wx-3.1.0/bin/wx-config $HOME/wx-3.1.0/bin/wx-config-3
  - user=$(echo $TRAVIS_REPO_SLUG | sed 's,/.*$,,')
  - cd ../ 
  - export GTEST=/home/travis/build/$user/googletest/googletest
  - export LKDIR=/home/travis/build/$user/lk
  - export WEXDIR=/home/travis/build/$user/wex
  - git clone https://github.com/$user/lk $LKDIR

script:
  - export PATH=$PATH:$HOME/wx-3.1.0/bin
  - pwd
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (make -j2 -C $LKDIR/build_linux && make -j2 -C $WEXDIR/build_linux); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (make -j2 -C $LKDIR/build_osx && make -j2 -C $WEXDIR/build_osx); fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgtk-3-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

branches:
  only:
  - master
  - develop
